export enum FILTER_TYPE_TAB_BAR {
  LOWER_COST,
  FASTER,
}

export enum FILTER_TYPE {
  'ALL' = 'ALL',
  'NO_TRANSFERS' = 'NO_TRANSFERS',
  'ONE_TRANSFERS' = 'ONE_TRANSFERS',
  'TWO_TRANSFERS' = 'TWO_TRANSFERS',
  'THREE_TRANSFERS' = 'THREE_TRANSFERS',
  'LOWER_COST' = 'LOWER_COST',
  'FASTER' = 'FASTER',
}

type PartFilter = FILTER_TYPE.ALL | FILTER_TYPE.NO_TRANSFERS | FILTER_TYPE.ONE_TRANSFERS | FILTER_TYPE.TWO_TRANSFERS | FILTER_TYPE.THREE_TRANSFERS;
type PartTabBar = FILTER_TYPE.LOWER_COST | FILTER_TYPE.FASTER;

export const FILTER_TYPE_PRESENTATION: Record<PartFilter, string> = {
  [FILTER_TYPE.ALL]: 'Все',
  [FILTER_TYPE.NO_TRANSFERS]: 'Без пересадок',
  [FILTER_TYPE.ONE_TRANSFERS]: 'Одня пересадка',
  [FILTER_TYPE.TWO_TRANSFERS]: 'Две пересадки',
  [FILTER_TYPE.THREE_TRANSFERS]: 'Три пересадки',
}

export const TAB_BAR_FILTER_TYPE_PRESENTATION: Record<PartTabBar, string> = {
  [FILTER_TYPE.LOWER_COST]: 'Самый дешевый',
  [FILTER_TYPE.FASTER]: 'Самый быстрый',
}